name: 'Longevity_Viz'
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.13
    - pandas=2.2
    - altair=5.5
    - ipykernel=6.29
    - altair-all=5.5
    - dash=2.18
    - dash-bootstrap-components=1.7
    - plotly=6.0
    - geopandas=1.0.*
    - tabulate=0.9  # df.to_markdown()
    - lxml=5.3  # pd.read_html()
    - pip=25.0
    - 
    - pip:
        - dash-vega-components
        - flask-caching==2.3
